In [1]:
import numpy as np
import pandas as pd 
from sklearn import model_selection

In [3]:
df_train = pd.read_csv("train.csv")
df_train["cat1_A"] = df_train["cat1"].apply(lambda x: 1 if x == "A" else 0)
df_train["cat8_C"] = df_train["cat8"].apply(lambda x: 1 if x == "C" else 0)
df_train["cat8_E"] = df_train["cat8"].apply(lambda x: 1 if x == "E" else 0)
df_train = df_train.drop(['cat0', 'cat1', 'cat2', 'cat3', 'cat4', 'cat6', 'cat7', 'cat9'], axis = 1)

In [5]:
df_train.head()

,id,cat5,cat8,cont0,cont1,cont2,cont3,cont4,cont5,cont6,...,cont8,cont9,cont10,cont11,cont12,cont13,target,cat1_A,cat8_C,cat8_E
0,1,B,C,0.201470,-0.014822,0.669699,0.136278,0.610706,0.400361,0.160266,...,0.389470,0.267559,0.237281,0.377873,0.322401,0.869850,8.113634,0,1,0
1,2,D,A,0.743068,0.367411,1.021605,0.365798,0.276853,0.533087,0.558922,...,0.594928,0.341439,0.906013,0.921701,0.261975,0.465083,8.481233,0,0,0
2,3,D,A,0.742708,0.310383,-0.012673,0.576957,0.285074,0.650609,0.375348,...,0.555205,0.843531,0.748809,0.620126,0.541474,0.763846,8.364351,1,0,0
3,4,D,C,0.429551,0.620998,0.577942,0.280610,0.284667,0.668980,0.239061,...,0.679618,0.574844,0.346010,0.714610,0.540150,0.280682,8.049253,0,1,0
4,6,D,A,1.058291,0.367492,-0.052389,0.232407,0.287595,0.686964,0.420667,...,0.684501,0.956692,1.000773,0.776742,0.625849,0.250823,7.972260,1,0,0

In [6]:
df_train["kfold"] = -1

In [7]:
kf = model_selection.KFold(n_splits=5, shuffle=True, random_state=42)
for fold, (train_indicies, valid_indicies) in enumerate(kf.split(X=df_train)):
    df_train.loc[valid_indicies, "kfold"] = fold

In [8]:
df_train.to_csv("train_folds.csv", index=False)